backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "basic-page"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - label: "Menu Items"
        name: "menuitems"
        widget: "list"
        fields: 
          - {label: "Menu title", name: "menutitle", widget: "string", required: "true"}
          - {label: "Menu path", name: "menupath", widget: "string", required: "true"}

  - name: "settings"
    label: "Settings"
    folder: "src/pages"
    files:
      - file: "src/pages/menu/index.md"
        label: "Menu Settings"
        name: "menusettings"
        fields:
          - label: "Menu Items"
            name: "menuitems"
            widget: "list"
            fields: 
              - {label: "Menu title", name: "menutitle", widget: "string", required: "true"}
              - {label: "Menu path", name: "menupath", widget: "string", required: "true"}
