backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "basic-page"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - label: "Website elements"
        name: "elements"
        widget: "list"
        fields:
          - label: "Element1"
            name: "element1"
            widget: "list"
            fields:
              - {label: Name, name: element1name, widget: string}
              - {label: Avatar, name: element1avatar, widget: image}
          - label: "Element2"
            name: "element2"
            widget: "list"
            fields:
              - {label: Name, name: element2name, widget: string}
              - {label: Avatar, name: element2avatar, widget: image}

  - name: "menu"
    label: "Menu"
    folder: "src/pages/menu"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "menu"}
      - {label: "Menu Title", name: "title", widget: "string"}
      - {label: "Menu path", name: "menupath", widget: "string"}
          